# Generated by Django 3.2.6 on 2021-09-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('1', 'Next'), ('2', 'Prev')], default=1, max_length=50),
        ),
    ]
