# Generated by Django 3.2.6 on 2021-09-04 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_vote_vote_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='vote_type',
        ),
    ]
